### ISSUE TITLE
ModuleNotFoundError: No module named '_ma_playback' issue

### ISSUE THREAD

**Issue by vanillafox0620** [plaaosert/credits_public#1]
After downloading and installing all the necessary packages (Colorama, just_playback, and keyboard), I started the credits.py in the terminal, and got the following error

  File "/home/<my_username>/Desktop/Credits/credits_public/just_playback/playback.py", line 8, in <module>
    from _ma_playback import ffi, lib
ModuleNotFoundError: No module named '_ma_playback'

**Comment by plaaosert** [comment]
This looks like a just_playback error. It would probably be best if you raised an issue there as I don't know the codebase. Sorry about the trouble.

https://github.com/cheofusi/just_playback/issues
