### ISSUE TITLE
no module named 'keyboard'

### ISSUE THREAD

**Issue by Andy4169** [plaaosert/credits_public#10]
i have run keyboard setup.py and still it shows this
![image](https://github.com/plaaosert/credits_public/assets/108393910/4e16d5b6-dff3-42f7-8f19-47c022e42bcf)

**Comment by plaaosert** [comment]
hey - sorry for the VERY long delay here - please try installing keyboard using pip (python -m pip install keyboard). additionally, please run this script in a command terminal as it won't work in IDLE

**Comment by TheFluffyGuy233** [comment]
Oh, sorry but im have a serius problem i cant fix
![Sin título](https://github.com/user-attachments/assets/2271bb98-f703-40db-8162-ad4d5a924ac7)
please help
