### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by SouceCalve** [plaaosert/credits_public#12]
After installing it runs ONLY in root, what disables the audio(ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave, alsa-utils installed), without root keyboard module isnt starting(ImportError: You must be root to use this library on linux.)
Updates please?

**Comment by plaaosert** [comment]
unfortunately that's not an issue i can solve; you'll need to raise an issue for the [keyboard](https://github.com/boppreh/keyboard) library.

as for audio problems, i wouldn't be able to help there either as that looks like an issue with [just-playback](https://github.com/cheofusi/just_playback), which is the library used for audio.
