### ISSUE TITLE
I cant fix this error,  please help

### ISSUE THREAD

**Issue by TheFluffyGuy233** [plaaosert/credits_public#13]
![Sin título](https://github.com/user-attachments/assets/f8d31139-38af-405b-9743-47232dd3b06b)
i cant fix that
i already put the song in the media folder
(yeah i know, that file is a litte old but i really wanted to test it :( )

**Comment by plaaosert** [comment]
make sure you're opening the file from the correct directory (credits_public-main), and that the file exists with the name exactly "credits.wav" in the media/ folder

**Comment by TheFluffyGuy233** [comment]
![image](https://github.com/user-attachments/assets/80c08fde-ab4f-4b70-930f-2fc29a64b539)
the same error.
I have already replaced the audio file, changed the name of the folder and downloaded the file again and nothing changed

If I have something wrong tell me,file locations are located here
The folder named "credits_public-main" "C:\Users\Estudiante\Desktop\credits_public-main"
and the .wav file named "credits.wav" "C:\Users\Estudiante\Desktop\credits_public-main\media\credits.wav"

The music file has a size of 52,124 KB

and, i need run this in a windows CMD? or only open the .py file. and if I need to start it in a cmd please tell me how
(im have windows 11)

(I appreciate your previous help)

**Comment by plaaosert** [comment]
You do need to run it in a command prompt.
I don't have Windows 11, but one of these methods should work:

1) Right-click on the folder in File Explorer **while holding down Shift** and click "Open PowerShell window here" or similar, then type `python credits.py` (or however else you invoke python),
2) Open the Start menu and type "cmd", hit Enter, then navigate to the folder and run `python credits.py`
3) Press Windows+R, type "cmd", hit Enter, then navigate to the folder and run `python credits.py`

video example:
[https://streamable.com/h071yj](https://streamable.com/h071yj)

**Comment by TheFluffyGuy233** [comment]
Omggg!!!! tysm
you fixed all my problems
thanks you alot for help me!
