### ISSUE TITLE
line 167: result = eval(args.expression)

### ISSUE THREAD

**Issue by HokoraYinphineMPP** [plaaosert/credits_public#2]
`Traceback (most recent call last):
  File "/usr/bin/py", line 167, in <module>
    result = eval(args.expression)
  File "<string>", line 1, in <module>
    credits.py
AttributeError: '_Printer' object has no attribute 'py'`

after install all needed libraries
i get this when trying to run credits.py
using python 3.8.10 for bash

if i use powershell i get 
`Traceback (most recent call last):
  File "D:\Downloads\credits_public-main\credits_public-main\credits.py", line 5, in <module>
    import keyboard
ModuleNotFoundError: No module named 'keyboard'`
despite already using pip to install keyboard
using python 3.9.6 for powershell

**Comment by plaaosert** [comment]
hey - is this on Windows or Linux? just making sure as this seems to be a dependency issue on linux (which would mean that when you built python it was missing a package and couldn't build a default library)

**Comment by plaaosert** [comment]
as for the powershell method it's very strange that it would fail to have a module directly installed. did you use the right version of pip (matching your py 3.9.6 install)?

**Comment by HokoraYinphineMPP** [comment]
actually i ended up going to C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages
and copying keyboard, just_playback, tinytag, _cffi_backend.cp39-win_amd64.pyd, and _ma_playback.pyd into D:\Downloads\credits_public-main\credits_public-main
it works on windows but not on linux (i use bash for virtual machine)

in retrospect it might be my screwed up PATHs but i dont know for sure
nevertheless it works. Great work on this!

**Comment by plaaosert** [comment]
oh yeah, you can locally install modules like that and it would work. sorry i couldn't be more help :[

**Comment by HokoraYinphineMPP** [comment]
no worries :)
should i close this issue or keep it up due to linux still not working?

**Comment by plaaosert** [comment]
I'll close it for now, thanks for your time though
