### ISSUE TITLE
Media not working

### ISSUE THREAD

**Issue by VoidGalaxy2356** [plaaosert/credits_public#6]
It keeps saying that it can't find "credits.wav" in the media folder; I literally put the credits.wav file in the media folder.  I'm even using Python 3.6.

**Comment by plaaosert** [comment]
Hey,

Can you provide a screenshot / paste of the error? It would also help to see the command you're using to run the script and where you're running it from.

Relative file paths are likely preventing you from opening the script if you're opening it from the wrong directory.

**Comment by VoidGalaxy2356** [comment]
The issue is fixed, I was just using NP++'s run feature.
