### ISSUE TITLE
Illegal instruction error

### ISSUE THREAD

**Issue by A765-ALEX** [plaaosert/credits_public#7]
Dunno what could be causing it. I found the core dump and attached it.
[core.python3.1000.9c37eda3268940b087f3095cded9d3f0.1833.1663863172000000.gz](https://github.com/plaaosert/credits_public/files/9627637/core.python3.1000.9c37eda3268940b087f3095cded9d3f0.1833.1663863172000000.gz)

**Comment by plaaosert** [comment]
Can I also get the exception including traceback if possible?

**Comment by A765-ALEX** [comment]
>[fakeusername@manjaro-usb credits_public]$ python3 credits.py 
>Illegal instruction (core dumped)
>[fakeusername@manjaro-usb credits_public]$ 

this is the only output I'm getting, sorry for replying late
maybe it's a problem with Linux or python, or it's just my hardware (I'm on a laptop with a 4th generation i5)

**Comment by A765-ALEX** [comment]
here's the neofetch output if it helps
fakeusername@manjaro-usb 
OS: Manjaro Linux x86_64 
Host: 20B7S1GT04 ThinkPad T440 
Kernel: 5.15.12-1-MANJARO 
Uptime: 5 hours, 17 mins 
Packages: 1435 (pacman) 
Shell: bash 5.1.12 
Resolution: 1600x900 
DE: Xfce 4.16 
WM: Xfwm4 
WM Theme: Matcha-sea 
Theme: Matcha-dark-sea [GTK2/3] 
Icons: Papirus-Maia [GTK2], Adwaita [GTK3] 
Terminal: xfce4-terminal 
Terminal Font: Hack 12 
CPU: Intel i5-4300U (4) @ 2.900GHz 
GPU: Intel Haswell-ULT 
Memory: 2043MiB / 7641MiB 
here's uname -a output:
Linux manjaro-usb 5.15.12-1-MANJARO #1 SMP PREEMPT Wed Dec 29 18:08:07 UTC 2021 x86_64 GNU/Linux

**Comment by plaaosert** [comment]
hey, it's likely this is a problem with an external library (such as just-playback or keyboard). i can't offer much more advice sadly :-(
