### ISSUE TITLE
Unable to run on Raspberry Pi 400

### ISSUE THREAD

**Issue by Ra1nnYT** [plaaosert/credits_public#8]
So I don't know how to describe this, but won't run on the Pi 400. It will only play the opening animation (only the frames where the text increases until it's all white).
I installed everything and updated everything. Originally it asked if I was root so I ran it as root and I only got the opening frames. While those frames were playing, I could view the individual sections, but instead of playing them frame-by-frame, they would instead print them as if they were static. Is there something I'm doing wrong?
Also the animation is amazing (viewed it on YouTube), you deserve more attention that you have, keep up the great work!

**Comment by plaaosert** [comment]
hey - i'm not sure what you mean by this. could you record a video of what's happening?

- re: "instead print them as if they were static", this sounds like your terminal isn't accepting ANSI correctly or is putting in line breaks where they shouldn't be (such as if the lines printed are longer than the length of a terminal row). try reducing the font size of the terminal or increasing the window size if you're using a window manager - the animation uses a few columns past the bounds of the actual animation bounds for clearance

**Comment by Ra1nnYT** [comment]
Alright, thanks. I'll try it and I'll let you know how it goes.

Update: It is fixed. Thanks!
(I tried to record a video as I didn't have one, but it worked.)

**Comment by TG20HD** [comment]
Alright, thanks. I'll try it and I'll let you know how it goes.

**Comment by plaaosert** [comment]
Nice! Good to hear.
